In [1]:
import numpy as np
from scipy.spatial.transform import Rotation as R

# Source quaternion and position
source_quat = [-9.835933849850075e-05, -3.1290452066124376e-05, 0.00032596024859776415, 0.9999999415481308]
source_pos = [0.01693921645885583, -0.0019361239704956653, 0.0006106553212857983]

# Target quaternion and position
target_quat = [1.2915154991739152e-07, 3.7550912103400815e-05, -0.00010055051711756224, 0.9999999942397528]
target_pos = [124.72284698486328, -198.7583770751953, 0.0017056845827028155]

# Convert quaternions to rotation matrices
source_rotation = R.from_quat(source_quat).as_matrix()
target_rotation = R.from_quat(target_quat).as_matrix()

In [2]:
# Compute the relative rotation
relative_rotation = target_rotation @ np.linalg.inv(source_rotation)

# Compute the relative translation
relative_translation = np.array(target_pos) - relative_rotation @ np.array(source_pos)

print("Relative Rotation Matrix:\n", relative_rotation)
print("Relative Translation Vector:\n", relative_translation)


Relative Rotation Matrix:
 [[ 9.99999627e-01  8.53042368e-04  1.37579008e-04]
 [-8.53015254e-04  9.99999617e-01 -1.97017487e-04]
 [-1.37747020e-04  1.96900057e-04  9.99999971e-01]]
Relative Translation Vector:
 [ 1.24705909e+02 -1.98756426e+02  1.09774383e-03]


In [3]:
from scipy.spatial.transform import Rotation as R
import numpy as np



# Convert rotation matrix to quaternion
rotation_quat = R.from_matrix(relative_rotation).as_quat()  # [x, y, z, w]

print("Quaternion (x, y, z, w):", rotation_quat)
print("Translation (x, y, z):", relative_translation)


Quaternion (x, y, z, w): [ 9.84793956e-05  6.88315138e-05 -4.26514447e-04  9.99999902e-01]
Translation (x, y, z): [ 1.24705909e+02 -1.98756426e+02  1.09774383e-03]
